### ISSUE TITLE
False Naming

### ISSUE THREAD

**Issue by furrki** [mcichecki/Combine-MVVM#4]
On Title and Description, you say that its a UIKit example but It's actually a SwiftUI Example.

**Comment by mcichecki** [comment]
@furrki can you give me example of SwiftUI code in this project? There is no SwiftUI import.

<img width="997" alt="Screenshot 2020-05-04 at 19 21 59" src="https://user-images.githubusercontent.com/9085461/80994116-893ed600-8e3c-11ea-9518-ce391e1c71b5.png">
