### ISSUE TITLE
Login sample is too trivial

### ISSUE THREAD

**Issue by pzmudzinski** [mcichecki/Combine-MVVM#5]
I think Login page would be way more helpful if it would present some fake validation of credentials along with "loading" / "error creds" UI states. Right now it just goes to next screen completely omitting ViewModel.

**Comment by mcichecki** [comment]
Do you mean using an asynchronous validation that would act as we would be making a request to get the response from the server when login button is tapped?

I know that this project is far from the real world example but it shows how you can use two way data binding on the login screen. The second screen deals a little bit with networking and handling errors.

**Comment by pzmudzinski** [comment]
Yeah, in addition how would you do such thing:
1. User presses the button, view model is doing API request, button is disabled, ViewController shows loader
2. If process fails, ViewController displays the error, if it succeeds, it goes to the next screen

Does ViewModel exposes `PassthroughSubject` for tap input? Does it exposes `AnyPublisher<Bool>` for loading and `AnyPublisher<Error>` for error result? (that's seems to be a lot of code for single thing) 
Or maybe it should use Swift's `Result` somehow? 🤔

**Comment by mcichecki** [comment]
I think you could use `@Published var isButtonEnabled: Bool = false` to bind it to the button's `\.isEnabled` property. The second variable that would tell us about the result of the request could be `PassthroughSubject<(), Error>()`. Then you would check if it produces error or value (`Void` in this case) and navigate to the second screen.
Maybe I will find time this weekend and implement this.

**Comment by pzmudzinski** [comment]
That would be great! 
I am just worried if app makes 100 requests you will end up with multiple variables for loading / success / error state. 
I am looking for any pattern used in iOS community and cannot find anything. 

Also if you use `PassthroughSubject<(), Error>` for login process once user types invalid character your subscription is going to be disposed, so no retries possible.

**Comment by mcichecki** [comment]
@pzmudzinski I submitted a PR (#6) with the example of what we've discussed.

**Comment by pzmudzinski** [comment]
Wow, this is absolute helpful. Thanks for spending time on it.

In meantime, I was thinking about slightly different approach:
ViewModel exposes something to trigger login process, e.g. `let loginTrigger = PasstroughSubject<Void, Never>` 

now ViewModel subscribes to it:
```swift
loginResult = loginTrigger
 .map { loginApiRequest(username, password) } 
 .switchToLatest()
```

and ViewController "binds" UIButton into trigger:
`button.tapPublisher().subscribe(viewModel.loginTrigger)`

finally ViewController can subscribe to `loginResult` to show error:
```swift
loginResult
 .materialize()
 .failures()
 .sink { error in showError(error) }
```

ViewModel can subscribe to call coordinator to move to the next scene.
What do you think about this approach? I feel its little bit too complicated (especially hooking UI might be annyoing) but allows for more code reuse.

**Comment by mcichecki** [comment]
I like your approach too but I will leave my approach since this example doesn't use any external dependencies.
